// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uufmxrrvcioeevxphxko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1Zm14cnJ2Y2lvZWV2eHBoeGtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMDQ4NjAsImV4cCI6MjA2Njg4MDg2MH0.Ms7wOKJX9auNDu-_a1Oi5q5J7h0uiEOSvf-br7ld_cA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});